import type { NextPage } from 'next'
import Head from 'next/head'
import {Navbar} from "../components/navbar/Navbar";

const Home: NextPage = () => {
  return (
      <div className='bg-gradient-to-t from-folpd-reds-dk to-folpd-reds-ruby'>
          <Navbar />
        <div className='w-full h-screen bg-bgimage bg-no-repeat bg-cover bg-center'>

          <Head>
            <title>Frame of Light Designs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>


        </div>
      </div>
  )
}

export default Home
