import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='w-full h-screen bg-bgimage bg-no-repeat bg-cover bg-center'>
      <Head>
        <title>Frame of Light Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}

export default Home
